### PR TITLE
delaunay.renderPoints(r)

### LINKED ISSUE #130: renderPoints(5) crashes
see https://talk.observablehq.com/t/d3-delaunay-renderpoints-how-to-set-the-radius-with-svg/5014

in https://github.com/d3/d3-delaunay#delaunay_renderPoints [context] is marked as optional, meaning that renderPoints(5) should be treated like renderPoints(null, 5)

https://github.com/d3/d3-delaunay/blob/main/src/delaunay.js#L176

### PR DESCRIPTION
**Pull request by Fil**
closes #130

### CODE REVIEW

File: src/delaunay.js [hunk 1]
```diff
@@ -174,6 +174,9 @@ export default class Delaunay {
     return buffer && buffer.value();
   }
   renderPoints(context, r = 2) {
+    if (arguments.length === 1 && ["number", "string"].includes(typeof context)) {
+      [r, context] = [+context, null];
+    }
```
Comment (mourner) [inline src/delaunay.js:179]: I'd prefer simpler code that doesn't use `arguments` and redundant array allocations.

```suggestion
    if (typeof +context === 'number') {
      r = +context;
      context = null;
    }
```

**Review by mourner — APPROVED** [review]

File: src/delaunay.js (hunk 1 above)
Comment (Fil) [reply src/delaunay.js]: I don't think this would work, since +null and +undefined are "number".
What we can do is test for "number-like" with `x != null && +x === +x`

Comment (mbostock) [inline src/delaunay.js]: Here’s my suggestion: the more specific type is *context* (an object that implements the CanvasPathMethods API), so we only consider the first argument a context if it implements *context*.moveTo. Otherwise we assume that the first argument is *r*, and set *context* to null. But we still need to default *r* to 2 if both arguments are undefined.

```suggestion
  renderPoints(context, r) {
    if (!context || typeof context.moveTo !== "function") r = context, context = null;
    if (r === undefined) r = 2;
```

Comment (mbostock) [reply src/delaunay.js]: We should probably also coerce *r* to a number (otherwise the `x + r` could result in string concatenation).

Comment (Fil) [reply src/delaunay.js]: > we only consider the first argument a context if it implements _context_.moveTo.

this breaks `renderPoints(null, 5)` which is currently only working solution for this task.

Since we're on a major version change we can include this breaking change, but if we want to be conservative we should only apply this if r === undefined

File: src/delaunay.js [hunk 2]
```diff
@@ -173,7 +173,9 @@ export default class Delaunay {
     this.renderHull(context);
     return buffer && buffer.value();
   }
-  renderPoints(context, r = 2) {
+  renderPoints(context, r) {
+    if (r === undefined  && (!context || typeof context.moveTo !== "function")) r = context, context = null;
+    r = (r == null) ? 2 : +r;
```
Comment (mbostock) [inline src/delaunay.js:178]: In the `renderPoints(context, null)` case, we still want `r` to be equal to `+null` = `0`. So how about a tiny tweak…

```suggestion
    if (r === undefined && (!context || typeof context.moveTo !== "function")) r = context, context = null;
    r = r == undefined ? 2 : +r;
```
