### PR TITLE
fix incorrect voronoi diagram for 5 collinear points

### LINKED ISSUE #146: Incorrect Voronoi Diagram for simple test case
For a certain array of 5 points the Voronoi diagram "misses" a point. I have reproduced this on [observable](https://observablehq.com/d/02b23af92458f45b).

image

I originally reported this as a bug in Vega-Lite Vega/vega-lite#9388 and then Vega Vega/vega#3941, but after more digging I believe the bug is coming from this library.

### PR DESCRIPTION
**Pull request by Fil**
This fixes #146 by adopting a simpler jittering strategy in the collinear case

<del>Sharing for discussion, because this "fix" is really feeble: if we increase the radius a little bit more (to 5e-8), another test breaks. I'd like to find a more robust approach.</del>

Maybe at some point we'll need to create a fake voronoi diagram from scratch, rather than replay with jittered points, but it seems that this is working well enough for now.

closes #146

### CODE REVIEW

**Review by mourner — APPROVED** [review]

File: src/delaunay.js [hunk 1]
```diff
@@ -56,14 +52,9 @@ export default class Delaunay {
...
-      const e = this.collinear[0], f = this.collinear[this.collinear.length - 1],
-        bounds = [ points[2 * e], points[2 * e + 1], points[2 * f], points[2 * f + 1] ],
-        r = 1e-8 * Math.hypot(bounds[3] - bounds[1], bounds[2] - bounds[0]);
-      for (let i = 0, n = points.length / 2; i < n; ++i) {
-        const p = jitter(points[2 * i], points[2 * i + 1], r);
-        points[2 * i] = p[0];
-        points[2 * i + 1] = p[1];
-      }
+      const e = this.collinear[0] << 1, f = this.collinear[this.collinear.length - 1] << 1;
+      const r = 1e-9 * Math.hypot(points[f] - points[e], points[f + 1] - points[e + 1]);
```
Comment (mbostock) [inline src/delaunay.js:56]: Is it guaranteed that the first and last point in `this.collinear` aren’t coincident? Do we need to compute the bounding box of the collinear points intead?

Comment (Fil) [reply src/delaunay.js:56]: Yes, they are sorted just above. e and f are the opposite extrema.

**Review by mbostock — APPROVED** [review]
